"""Pydantic models for the Skuggspel plugin."""

import time

from pydantic import BaseModel, Field


class ShadowProfile(BaseModel):
    """Describes the shadow side of an identity."""

    identity_name: str
    shadow_description: str
    inverted_traits: dict[str, str] = {}
    shadow_voice: str = ""
    framework: str = ""


class ShadowPost(BaseModel):
    """A piece of content generated by an identity's shadow self."""

    identity_name: str
    display_name: str = ""
    topic: str
    shadow_content: str
    original_content: str = ""
    shadow_profile: ShadowProfile
    generated_at: float = Field(default_factory=time.time)
    word_count: int = 0

    def model_post_init(self, __context) -> None:
        if not self.word_count:
            object.__setattr__(self, "word_count", len(self.shadow_content.split()))
