"""
Data models for the Whallet Trader plugin.

Defines the structure for trading signals, orders, executions, portfolio
positions, and risk parameters used throughout the trading system.
"""

import uuid
from datetime import datetime
from decimal import Decimal
from enum import Enum
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class TradeAction(str, Enum):
    """Trading actions for Polymarket."""

    BUY_YES = "BUY_YES"
    BUY_NO = "BUY_NO"
    SELL_YES = "SELL_YES"
    SELL_NO = "SELL_NO"
    CLOSE_POSITION = "CLOSE_POSITION"


class OrderStatus(str, Enum):
    """Status of a trade order."""

    PENDING = "pending"  # Created but not yet submitted
    SUBMITTED = "submitted"  # Submitted to blockchain
    CONFIRMING = "confirming"  # Waiting for confirmation
    COMPLETED = "completed"  # Successfully executed
    FAILED = "failed"  # Execution failed
    CANCELLED = "cancelled"  # Cancelled by user or system


class OrderType(str, Enum):
    """Type of trade order."""

    MARKET = "market"  # Execute at current market price
    LIMIT = "limit"  # Execute at specified price or better
    STOP_LOSS = "stop_loss"  # Execute when price reaches stop level
    TAKE_PROFIT = "take_profit"  # Execute when price reaches profit target


class RiskLevel(str, Enum):
    """Risk level for a trade signal."""

    LOW = "low"  # High confidence, small edge
    MEDIUM = "medium"  # Moderate confidence, moderate edge
    HIGH = "high"  # Lower confidence, larger edge
    EXTREME = "extreme"  # Speculative, very large edge


class TradeSignal(BaseModel):
    """
    A trading signal generated by the polymarket_monitor plugin.

    Contains all information needed to evaluate and potentially execute
    a trade on Polymarket.
    """

    signal_id: str = Field(default_factory=lambda: f"sig_{uuid.uuid4().hex[:8]}")

    # Market information
    market_id: str
    market_question: str
    market_slug: str | None = None
    category: str | None = None

    # Trading parameters
    action: TradeAction
    outcome: str  # "YES" or "NO"
    market_price: Decimal  # Current market price (0.00-1.00)
    our_probability: Decimal  # Our estimated probability (0.00-1.00)
    probability_edge: Decimal  # Absolute edge: |our_prob - market_price|

    # Signal quality
    confidence_score: float  # 0-100 confidence in our probability estimate
    volume_score: float  # 0-100 based on trading volume/liquidity
    time_horizon_days: float  # Expected days until resolution

    # Position sizing (suggested by monitor)
    suggested_position_size_percent: Decimal  # % of portfolio (0-5%)
    suggested_position_size_usd: Decimal | None = None  # Absolute USD amount
    kelly_fraction: Decimal  # Kelly criterion suggested position size (0-1)

    # Risk assessment
    urgency: str  # "low", "medium", "high", "critical"
    risk_level: RiskLevel = RiskLevel.MEDIUM

    # Execution preferences
    order_type: OrderType = OrderType.MARKET
    limit_price: Decimal | None = None  # For limit orders
    allow_simulation: bool = True  # Allow execution in simulation mode

    # Metadata
    detected_at: datetime = Field(default_factory=datetime.now)
    expires_at: datetime | None = None  # Signal expiration time
    source: str = "polymarket_monitor"  # Source plugin
    retry_count: int = 0  # Number of retry attempts

    model_config = ConfigDict(from_attributes=True)


class TradeOrder(BaseModel):
    """
    A trade order ready for execution.

    Created from a TradeSignal after risk management checks and
    position size calculations.
    """

    order_id: str = Field(default_factory=lambda: f"ord_{uuid.uuid4().hex[:8]}")
    signal_id: str  # Reference to source signal

    # Market information
    market_id: str
    market_question: str
    outcome: str  # "YES" or "NO"

    # Order details
    action: TradeAction
    order_type: OrderType
    quantity: Decimal  # Number of tokens to buy/sell
    limit_price: Decimal | None = None  # For limit orders

    # Calculated fields
    estimated_price: Decimal  # Estimated execution price
    position_size_usd: Decimal  # Total USD value of position
    max_slippage_percent: Decimal = Decimal("0.01")  # 1% max slippage

    # Risk parameters
    stop_loss_price: Decimal | None = None
    take_profit_price: Decimal | None = None
    risk_level: RiskLevel

    # Status tracking
    status: OrderStatus = OrderStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.now)
    submitted_at: datetime | None = None
    completed_at: datetime | None = None
    error_message: str | None = None

    # Blockchain transaction details (filled after submission)
    transaction_hash: str | None = None
    gas_price_gwei: Decimal | None = None
    gas_limit: int | None = None

    model_config = ConfigDict(from_attributes=True)

    @classmethod
    def from_signal(cls, signal: TradeSignal, position_size_usd: Decimal) -> "TradeOrder":
        """Create a TradeOrder from a TradeSignal and calculated position size."""
        # Calculate quantity based on position size and market price
        # For Polymarket, price is per share (0.00-1.00), so quantity = USD / price
        if signal.market_price > 0:
            quantity = position_size_usd / signal.market_price
        else:
            quantity = Decimal("0")

        return cls(
            signal_id=signal.signal_id,
            market_id=signal.market_id,
            market_question=signal.market_question,
            outcome=signal.outcome,
            action=signal.action,
            order_type=signal.order_type,
            quantity=quantity,
            limit_price=signal.limit_price,
            estimated_price=signal.market_price,
            position_size_usd=position_size_usd,
            risk_level=signal.risk_level,
        )


class TradeExecution(BaseModel):
    """
    A completed trade execution.

    Created when a TradeOrder is successfully executed on-chain.
    Contains all details of the actual execution (price, gas used, etc.)
    """

    execution_id: str = Field(default_factory=lambda: f"ex_{uuid.uuid4().hex[:8]}")
    order_id: str  # Reference to source order
    signal_id: str  # Reference to source signal

    # Market information
    market_id: str
    market_question: str
    outcome: str  # "YES" or "NO"

    # Execution details
    action: TradeAction
    quantity: Decimal  # Actual quantity executed
    execution_price: Decimal  # Actual execution price
    position_size_usd: Decimal  # Actual USD value

    # Blockchain details
    transaction_hash: str
    block_number: int
    gas_used: int
    gas_price_gwei: Decimal
    gas_cost_usd: Decimal | None = None  # Gas cost in USD

    # Slippage and fees
    expected_price: Decimal  # Expected price at order time
    slippage_percent: Decimal  # Actual vs expected price difference
    fees_usd: Decimal | None = None  # Trading fees in USD

    # Simulation flag
    simulation: bool = False  # True if this was a simulated trade

    # Metadata
    executed_at: datetime = Field(default_factory=datetime.now)

    model_config = ConfigDict(from_attributes=True)


class PortfolioPosition(BaseModel):
    """
    A position held in a Polymarket market.

    Tracks ownership of YES/NO tokens with current value and P&L.
    """

    position_id: str = Field(default_factory=lambda: f"pos_{uuid.uuid4().hex[:8]}")

    # Market information
    market_id: str
    market_question: str
    outcome: str  # "YES" or "NO"

    # Position details
    quantity: Decimal  # Number of tokens held
    average_price: Decimal  # Weighted average purchase price
    current_price: Decimal  # Current market price
    invested_amount: Decimal  # Total USD invested
    current_value: Decimal  # Current USD value (quantity * current_price)

    # P&L calculations
    unrealized_pnl: Decimal  # Current value - invested amount
    unrealized_pnl_percent: Decimal  # (unrealized_pnl / invested_amount) * 100

    # Risk management
    stop_loss_price: Decimal | None = None
    take_profit_price: Decimal | None = None
    max_position_size: Decimal | None = None  # Maximum allowed size in USD
    position_size_percent: Decimal | None = None  # % of portfolio

    # Metadata
    first_bought: datetime
    last_updated: datetime = Field(default_factory=datetime.now)

    model_config = ConfigDict(from_attributes=True)


class RiskParameters(BaseModel):
    """
    Risk management parameters for trading.

    Used by the RiskManager to evaluate and constrain trading activity.
    """

    # Position limits
    max_position_size_percent: Decimal = Decimal("5.0")  # Max 5% of portfolio per trade
    max_portfolio_exposure_percent: Decimal = Decimal("25.0")  # Max 25% total exposure

    # Loss limits
    daily_loss_limit_percent: Decimal = Decimal("2.0")  # Max 2% daily loss
    weekly_loss_limit_percent: Decimal = Decimal("5.0")  # Max 5% weekly loss
    max_drawdown_percent: Decimal = Decimal("10.0")  # Max 10% peak-to-trough

    # Trading constraints
    min_probability_edge: Decimal = Decimal("0.03")  # 3% minimum edge
    min_confidence_score: float = 60.0  # 60/100 minimum confidence
    min_volume_usd: Decimal = Decimal("1000.0")  # $1,000 minimum 24h volume

    # Order constraints
    max_slippage_percent: Decimal = Decimal("0.02")  # 2% max slippage
    max_gas_price_gwei: Decimal = Decimal("100.0")  # 100 Gwei max gas price

    # Time-based constraints
    max_trades_per_day: int = 10
    cooloff_period_seconds: int = 300  # 5 minutes between trades

    model_config = ConfigDict(from_attributes=True)


class RiskCheckResult(BaseModel):
    """
    Result of a risk management check for a trading signal.

    Indicates whether a signal should be executed and any constraints
    that should be applied.
    """

    approved: bool  # Whether the signal passes risk checks
    reason: str | None = None  # Reason for approval/rejection

    # Risk assessment
    risk_level: RiskLevel = RiskLevel.MEDIUM
    risk_score: float  # 0-100 risk score (higher = riskier)

    # Constraints (if approved)
    max_position_size_usd: Decimal | None = None
    recommended_position_size_usd: Decimal | None = None
    required_stop_loss: Decimal | None = None
    required_take_profit: Decimal | None = None

    # Warnings
    warnings: list[str] = Field(default_factory=list)

    model_config = ConfigDict(from_attributes=True)


class TradingPerformance(BaseModel):
    """
    Trading performance metrics.

    Tracks P&L, win rate, risk-adjusted returns, and other key metrics
    for performance evaluation.
    """

    # Time period
    period_start: datetime
    period_end: datetime

    # Basic metrics
    total_trades: int
    winning_trades: int
    losing_trades: int

    # P&L
    total_pnl_usd: Decimal
    total_pnl_percent: Decimal

    # Risk-adjusted returns
    sharpe_ratio: Decimal | None = None
    sortino_ratio: Decimal | None = None
    max_drawdown_percent: Decimal

    # Win/loss statistics
    win_rate_percent: Decimal  # (winning_trades / total_trades) * 100
    average_win_usd: Decimal
    average_loss_usd: Decimal
    profit_factor: Decimal  # (gross_profits / gross_losses)

    # Position statistics
    average_position_size_usd: Decimal
    average_holding_period_days: Decimal

    # Risk metrics
    volatility_percent: Decimal | None = None
    value_at_risk_95_usd: Decimal | None = None

    model_config = ConfigDict(from_attributes=True)
